const uno =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis turpis vel sem posuere tristique. Praesent scelerisque blandit ligula vitae malesuada. Pellentesque luctus sodales hendrerit. Etiam id feugiat magna. Proin congue velit at dictum mattis. Nam faucibus, elit a tempus condimentum, libero nisi convallis sapien, non dapibus diam augue in dolor. Phasellus eu neque quis neque pharetra vehicula. Pellentesque eu urna turpis. Cras a purus sed lectus dictum porttitor nec eu nisi. Integer facilisis, erat tincidunt pulvinar vestibulum, felis nisl tristique quam, nec congue enim lorem vitae dolor. Cras ullamcorper elit at tempus imperdiet. Nulla vitae libero nec ex tristique sollicitudin id quis mauris. Curabitur ut mi volutpat, hendrerit ipsum sit amet, dignissim nulla. Quisque at auctor neque. Nulla non feugiat enim. ";

const dos =
    "Aenean pretium fermentum sapien in accumsan. Nullam laoreet mauris ac lorem congue malesuada. Vestibulum tempor porttitor nisl, eu pulvinar neque dignissim vitae. Praesent nec quam sit amet justo suscipit porttitor. Etiam sapien dui, eleifend et neque sed, rhoncus placerat nulla. Suspendisse rhoncus pulvinar erat, vel elementum ipsum. Cras cursus risus sed purus elementum auctor dapibus nec orci. Sed massa mi, sollicitudin et elementum et, faucibus sed justo. Vestibulum at eleifend erat, eget efficitur neque. Nam ultrices neque vel ligula feugiat, eu scelerisque justo sollicitudin. ";

const tres =
    "Nullam luctus libero sed dolor lacinia, non dignissim odio laoreet. Vivamus cursus dictum nisl facilisis cursus. Integer commodo quam nisl, in porta enim tristique aliquam. Etiam quis mollis turpis. Maecenas a leo dolor. Duis pharetra felis ultricies ligula euismod eleifend. Curabitur rutrum, sapien quis tristique feugiat, nisi leo bibendum tortor, id euismod nisl est ac magna. In tincidunt mi ut urna volutpat, et mollis nulla fringilla. Fusce vulputate mi nisi, rhoncus sodales tellus porttitor quis. Vivamus mattis vel nisi ut euismod. Mauris aliquam, diam sed vehicula porta, orci orci rhoncus mauris, vitae tristique odio risus ut nulla. ";

export { uno, dos, tres };
